dsrvlabs/vatz

.github/workflows/golangci-lint.yml
main.go

---
**Related:** #196
**Summary**
- Add github action for Golang lint
---
- ~@xellos00 Please add token named `GOLANG_LINT_ACTION_TOKEN`~
- Change token name from `GOLANG_LINT_ACTION_TOKEN`to `PR_ACTION_TOKEN`

Add github action golangci-lint 

---

sdk/README.md

---
**Summary**
- github.com/dsrvlabs/vatz-proto/plugin/v1
- github.com/dsrvlabs/vatz/sdk
- Delete step 2 which is no longer needed because the above repositories have been converted to public.
---

Edit sdk README.md

---

.github/workflows/ci_pr_reminder.yaml

---
make DISCORD_WEBHOOK as global
**Related:** 
close #330
**Summary**
---

Error on send a notification 

---

manager/healthcheck/healthcheck.go

---
**Related:** #360 
**Summary**
fix bug of panic when the healthcheck send notification to pagerduty.
---

Fix healthcheck msg

---

README.md

Update READMe.md
---
**Summary**
---

Edit README.md (#356)

---

manager/plugin/plugin.go
manager/plugin/plugin_test.go

---
**Related:** #362 
**Summary**
split arguments for start command.
---

Split arguments for start CLI command

---

README.md
docs/cli.md

---
close #350 
**Summary**
Add CLI documents.
---

Add docs for CLI

---

README.md

---
close #376 
**Summary**
Add link for release.

Add a link for Release Note

---

cmd/start.go

keep the same log format between stdout and file output.
---
Related: #380 
**Summary**
---

Align log format

---

.github/workflows/ci_pr_notifier.yaml

---
close #375 
**Summary**
There's error due to github's policy since dependabot has no access to secret when github action is triggered.

Sending A notification PRs from forked repo

---

README.md

- Add Feedback request, and contributing.
- Add Official plugins infos
---
close #394 
close #399 
---

Update README.md with feedback comments and official plugins. 

---

README.md

---
relate: #394 
Update Missed Typos in README.md

Update Missed Typos in README.md

---

LICENSE

---
close #406
**Summary**
Add Company name and year in License. 
---

add License with DSRV company name

---

cmd/start.go
monitoring/prometheus/metric.go
monitoring/prometheus/metric_test.go
monitoring/prometheus/prometheus.go
monitoring/prometheus/prometheus_test.go
utils/utils.go
utils/utils_test.go

---
Close #390 
**Summary**
Separate Monitoring in folder structures and add some test cases. 
---

Separate Monitoring in folder structures

---

sdk/go.mod
sdk/go.sum

---
related #410 
**Summary**
there's found Service vulnerability from security bot from git 
so updated to recommended updates.  
---

Update Denial of Service vulnerability

---

cmd/cmd.go
cmd/cmd_test.go
cmd/init.go
cmd/plugin.go
cmd/plugin_test.go
cmd/start.go
manager/config/config.go
manager/config/config_test.go
manager/config/fixtures.go
manager/plugin/db.go
manager/plugin/plugin.go

---
close #426 
**Summary**
Add home directory of VATZ on config file and all related commands load vatz home from config.
---

Add home path on the config

---

.github/workflows/create-vatz-bi-weekly.yml

---
**Related:** #417 
**Summary**
This is CI that creates Discussion every two weeks.
---
Adding labels through CI will be uploaded soon. 

Add CI about creation discussion w/o labels.

---

.github/workflows/create-vatz-bi-weekly.yml

---
**Related:** #417 
**Summary**
---
---
```sh
$ make coverage
ok  	github.com/dsrvlabs/vatz/cmd	10.351s	coverage: 20.2% of statements
ok  	github.com/dsrvlabs/vatz/manager/api	1.265s	coverage: 0.0% of statements [no tests to run]
ok  	github.com/dsrvlabs/vatz/manager/config	0.525s	coverage: 79.4% of statements
ok  	github.com/dsrvlabs/vatz/manager/dispatcher	2.170s	coverage: 7.8% of statements
ok  	github.com/dsrvlabs/vatz/manager/executor	1.660s	coverage: 68.9% of statements
ok  	github.com/dsrvlabs/vatz/manager/healthcheck	3.220s	coverage: 46.5% of statements
ok …
```

Fixed bug about wrong setting Authorization part

---

cmd/init.go

---
Related: #436 
**Summary**
There's was a miss typing in line in init.go during merge. 
---

line up in cmd format in init.go

---

cmd/plugin.go
docs/cli.md

---
**Related:** #450
**Summary**
- update CLI example and cli.md
---

update CLI example

---

README.md

---
**Related:** #475 
**Summary**
Version & License badge should be
v1.0.0 & GPL-3.0
---
```
dongyookang DK 🐸   ~/ffplay/GolandProjects/xellos/vatz   ISSUE-475
ok      github.com/dsrvlabs/vatz/cmd    3.211s  coverage: 23.5% of statements
ok      github.com/dsrvlabs/vatz/manager/api    0.572s  coverage: 0.0% of statements [no tests to run]
ok …
```

Fix version badge on README.md -> v1.0.0-RC.1

---

README.md

---
Close #475 
**Summary**
Missed to update badge for v1.0.0
---
```
dongyookang DK 🐸   ~/ffplay/GolandProjects/xellos/vatz   ISSUE-475
ok      github.com/dsrvlabs/vatz/cmd    3.211s  coverage: 23.5% of statements
ok      github.com/dsrvlabs/vatz/manager/api    0.572s  coverage: 0.0% of statements [no tests to run]
ok …
```

Fix version & license badge on README.md

---

cmd/plugin.go

---
close #481 
**Summary**
Enable `--config` flag for `plugin` subcommands.
---

Add global flag --config for plugin

---

.github/workflows/ci_coverage.yml

---
close #248
**Summary**
---

Auto make coverage 

---

.github/workflows/ci_coverage.yml

---
close #197
**Summary**
Error occurred due to python version and therefore upgrade with latest stable version that found at [version-manifest.json](https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json)
---

Update python-version on ci_coverage.yml with latest stable version.

---

go.mod
go.sum

---
#507 
**Summary**
~~This PR is just testing purpose of the new version of the protobuf files.
The commit will be updated again after merge the PR from `vatz-proto` side.~~
The new commit is pushed by apply the `main` branch of `vatz-proto`.
---

Apply the new version of proto

---

cmd/start.go
manager/dispatcher/discord.go
manager/dispatcher/telegram.go
manager/healthcheck/general_healthcheck.go
manager/healthcheck/healthcheck_test.go

---
close #500 
close #519
**Summary**
must stop the process if all notification channels are fail to send notifications. 
---

Stop VATZ process if all notification channels fail to send notifications

---

manager/healthcheck/general_healthcheck.go

---
close #521 
**Summary**
Make build successfully run
---
```
dongyookang DK 🍻   ~/ffplay/GolandProjects/xellos/vatz   ISSUE-521
ok      github.com/dsrvlabs/vatz/cmd    3.262s  coverage: 23.7% of statements
ok      github.com/dsrvlabs/vatz/manager/api    1.689s  coverage: 0.0% of statements [no tests to run]
ok      github.com/dsrvlabs/vatz/manager/config 2.135s  coverage: 77.8% of statements
ok …
```

Add library fmt

---

cmd/init.go
manager/dispatcher/dispatcher.go
manager/dispatcher/slack.go
manager/types/dispatcher.go

---
close #533 
**Summary**
Add a new dispatcher slack that can send notification to slack. 
---
```
ok      github.com/dsrvlabs/vatz/cmd    2.434s  coverage: 23.7% of statements
ok      github.com/dsrvlabs/vatz/manager/api    0.314s  coverage: 0.0% of statements [no tests to run]
ok      github.com/dsrvlabs/vatz/manager/config 0.773s  coverage: 77.8% of statements
ok …
```

Add new dispatcher Slack

---

.github/workflows/ci_coverage.yml

---
close #523 
**Summary**
Error fix on github action that is found at 
-  https://github.com/dsrvlabs/vatz/actions/runs/7393889193/job/20114433288?pr=536
---

Fix issue 523 

---

cmd/cmd.go
cmd/plugin.go
cmd/start.go
cmd/stop.go
manager/config/config.go
manager/plugin/plugin.go
utils/utils.go
utils/utils_test.go

---
close #512 
**Summary**
As previously explained this, PR include to unify format of plugin cli command 
---

unify plugin CLI commands

---

cmd/cmd.go
cmd/init.go
cmd/start.go
cmd/stop.go
docs/api.md
docs/cli.md
docs/design.md
docs/installation.md
docs/workflow.md

---
close #175 
**Summary**
Update documentation for release 1.1
---

Update all doc for release 1.1

---

README.md

---
close #544 
**Summary**
Missed to update version from 1.0.0 to 1.1.0
---

Update wrong version on README.md

---

manager/dispatcher/discord.go

---
**Related:** #576
**Summary**
---
Add new discord webhook address type.

Add new discord webhook address type

---

docs/community_plugins.md
docs/design.md
docs/installation.md
script/simple_start_guide/readme.md

---
close #596
**Summary**
Update and revise all documents which has been upgrade since last release v1.1.0
---

Update documents for release v1.2.0

---

README.md

update version label from v1.1.0 to v1.2.0
---
close #607 
**Summary**
Update an issue to v1.2.0
---

Update version 1.2.0

---

.github/workflows/create-vatz-bi-weekly.yml

- Related: https://github.com/dsrvlabs/vatz/discussions/614#discussioncomment-11765847

Action - Remove the schedule of creating vatz discussion
