dsrvlabs/vatz

- manager/dispatcher/discord.go
- manager/dispatcher/dispatcher.go
- manager/dispatcher/dispatcher_test.go
- manager/dispatcher/pagerduty.go
- manager/dispatcher/telegram.go
- manager/healthcheck/general_healthcheck.go
- manager/types/dispatcher.go
---
Add Options in ReqMsg to use unique name in key
close #314
**Summary**
previously, only plugin's method name has used as key to store plugins, it would be malfunctional if there's same plugin & method name in config.yaml. It's has been fixed by @gnongs but didn't fix it on pagerduty because it hadn't developed when he send PR.  
This PR fix pagerduty to use a sync.map's key with plugin + address + port so it fix use method name as key in pagerduty.go
---
> Add Options in ReqMsg to use unique name in key

- cmd/plugin.go
- go.mod
- go.sum
- manager/plugin/db.go
- manager/plugin/db_test.go
- manager/plugin/plugin.go
- manager/plugin/plugin_test.go
---
close #320 
**Summary**
List command of plugin that are installed on local machine.
```
~$ ./vatz plugin install https://github.com/dsrvlabs/vatz-plugin-cosmoshub/plugins/node_active_status cosmos-status
~$ vatz plugin list
```
---
> List command of plugin

- .gitignore
- cmd/plugin.go
- manager/plugin/plugin.go
- manager/plugin/plugin_test.go
---
close #322 
**Summary**
If the plugin is started by `vatz plugin` command, the output log will be stacked file.
By default, the log file will be created at vatz's plugin directory($HOME/.vatz)
and the file name will be same to plugin's name.
But the user specify `--log` argument like below, the log file will be created at exact location.
```
rootwarp@mindhack ~/g/vatz log > ./vatz plugin start --plugin cosmos-status --args "--valoperAddr=cosmosvaloper1wlagucxdxvsmvj6330864x8q3vxz4x02rmvmsu" --log ./status.log
```
The log file will be created if the log file is not exist or the log contents will be appended into the old file.
---
> Please, …
> #322: Redirect plugin's log

- README.md
- cmd/version.go
---
close #405 
**Summary**
Add a new official icons from @Jihoo-Designer and add Ascii mark on CLI command `version`
```
dongyookang DK 🚀   ~/ffplay/GolandProjects/xellos/vatz   ISSUE-405 ±
 ./vatz version
@@@@@@@@@@@@@@@         @@@@@@@@@@@@@@@@@@@                  
#@@@@@@@@@@@@@@@           @@@@@@@@@@@@@.                   
@@@@@@@@@@@@@@@              &@@@@@@@                     
@@@@@@@@@@@@@@@&            ,@@@@@.                      
@@@@@@@@@@@@@@@           ,@@@@                        
@@@@@@@@@@@@@@@(         ,@@/                         
.@@@@@@@@@@@@@@@        ,@                           
@@@@@@@@@@@@@@@.      . …
```
> Add new official icons for VATZ 

- Makefile
- cmd/init.go
- manager/plugin/db.go
- manager/plugin/db_test.go
- manager/plugin/plugin.go
- manager/plugin/plugin_test.go
- manager/types/dispatcher.go
---
close #421 
**Summary**
Initialize DB when `vatz init` executed.
---
> Initialize DB when VATZ is initialized.

- cmd/cmd.go
- cmd/cmd_test.go
- cmd/init.go
- manager/plugin/plugin.go
- manager/types/cmd.go
---
close #429
**Summary**
Add initializer for CLI command `init` to avoid overriding while its on coverage test.
---
go coverage should not affected on VATZ running.
> Avoid overriding DB while its on coverage test.

- cmd/plugin.go
- cmd/start.go
- manager/plugin/db.go
- manager/plugin/db_test.go
- manager/plugin/plugin.go
- utils/utils.go
---
close #388
**Summary**
Update plugins CLIs for following
- plugin enable/disable status
- plugin uninstall
update execute behaviors with plugins status
- added new columns is_enabled into table plugin
---
```
ok      github.com/dsrvlabs/vatz/cmd    1.172s  coverage: 18.0% of statements
ok      github.com/dsrvlabs/vatz/manager/api    0.134s  coverage: 0.0% of …
```
> Store a plugin status to not to send notification while VATZ is running when we stop in purpose

- docs/installation.md
- go.mod
- Update go mod from 1.18 -> 1.19
- Add install guide for go lang and its version installation.md.
---
close #397  
Refer to https://github.com/dsrvlabs/vatz/issues/397#issuecomment-1488605198
---
> State Golang is requirements to run VATZ

- cmd/plugin.go
---
close #439 
**Summary**
Fix `uninstall` and `status` command.
`PreRunE` is required on cobra command to instantiate config instance before running the command.
---
> Fix. config instance should be loaded before execute CLI.

- cmd/cmd_test.go
- cmd/init.go
---
close #444 
**Summary**
We do not use --home flag in CLI `vatz init` anymore since homepath is set up in config yaml file. 
- Extended default reminder schedule interval from 15 to 30
- Removed --home setting from command `vatz init`
---
```
✘ dongyookang DK 💡   ~/ffplay/GolandProjects/xellos/vatz   ISSUE-444
ok      github.com/dsrvlabs/vatz/cmd    1.092s  coverage: 18.3% of statements
ok …
```
> Remove flag `--home` in CLI command `vatz init`

- cmd/init.go
…ing in config yaml file.
---
close #436 
**Summary**
develop vatz init that provide official plugins default port numbers and name. 
---
```
dongyookang DK 💡   ~/ffplay/GolandProjects/xellos/vatz   ISSUE-436-RE ±
 make coverage                                                                                                                           
ok …
```
> Add new flag `--all` on CLI command `vatz init`

- manager/config/config.go
- manager/dispatcher/discord.go
- manager/dispatcher/dispatcher.go
- manager/dispatcher/mock_Dispatcher.go
- manager/dispatcher/pagerduty.go
- manager/dispatcher/telegram.go
- manager/types/dispatcher.go
---
**Related:** 
#344
**Summary**
Fix lint in config, dispatcher
---
> Fix lint in config, dispatcher

- manager/dispatcher/discord.go
- manager/dispatcher/telegram.go
---
Close #465 
**Summary**
If there's no cron entry was initialized and reminderState was off too, it could be cause panic as below.
This patch allowed to remove and stop the cron job, only if it is exist.
```
panic: interface conversion: interface {} is nil, not []cron.EntryID
goroutine 41 [running]:
github.com/dsrvlabs/vatz/manager/dispatcher.(*telegram).SetDispatcher(0xc000138600, 0x30?, {0xc0?, 0x9c821a?}, {{0xc00013e8d0, 0x10}, {0xc00013e930, 0xb}, {0xc00013e8f0, 0x9}, ...})
/root/git/vatz/manager/dispatcher/telegram.go:60 +0x37a
github.com/dsrvlabs/vatz/manager/executor.(*executor).Execute(0xedc0b7210?, {0xe1da48, 0xc00003a120}, …
```
> Check the cron entry initialized in dispatcher

- main.go
---
realted: #469 
**Summary**
as issue 
- #469, pretty much every CLI commands panics when there's error. 
so it hide those panic messages 
---
```
dongyookang DK 🔑   ~/ffplay/GolandProjects/xellos/vatz   ISSUE-469
ok      github.com/dsrvlabs/vatz/cmd    14.427s coverage: 23.5% of statements
ok      github.com/dsrvlabs/vatz/manager/api …
```
> fix panic message when all CLI commands fails.

- cmd/cmd.go
- cmd/init.go
- cmd/plugin.go
- cmd/start.go
- main.go
- manager/config/config.go
- manager/executor/general_executor.go
- manager/plugin/db.go
- manager/plugin/plugin.go
- utils/logs.go
---
close: #485 
**Summary**
As explained,  on #485
-  [Case 1](https://github.com/dsrvlabs/vatz/issues/485#issuecomment-1661065595), `Info` level logs are recorded on the logs as default unless user enable debug mode with flag `debug` which's showing all traceable `debug` logs. 
- [Case 2](https://github.com/dsrvlabs/vatz/issues/485#issuecomment-1661065785),  running Vatz doesn't clear show its even drives per its log level including `Info` `debug`, and `trace` 
---
```
dongyookang DK 🐵   ~/ffplay/GolandProjects/xellos/vatz   ISSUE-485
?       github.com/dsrvlabs/vatz        [no …
```
> Divide Logs by its level Debug, Info, trace. 

- cmd/start.go
- monitoring/prometheus/metric.go
- monitoring/prometheus/metric_test.go
- monitoring/prometheus/prometheus.go
- monitoring/prometheus/prometheus_test.go
- utils/utils.go
---
close #312
close #503 
**Summary**
Print log that if client to plugin connected succesfully. 
---
```
✘ dongyookang DK 👑   ~/ffplay/GolandProjects/xellos/vatz   ISSUE-312-re ±
ok      github.com/dsrvlabs/vatz/cmd    6.020s  coverage: 23.4% of statements
ok      github.com/dsrvlabs/vatz/manager/api    0.768s  coverage: 0.0% of statements [no tests to run]
ok …
```
> Add log client connected to plugin successfully.

- manager/executor/general_executor.go
- sdk/README.md
- sdk/grpc.go
- sdk/sdk.go
- sdk/sdk_test.go
---
related #499 
**Summary**
in the response, there' AlertType which doesn't used anywhere. 
so trying to remove it. 
---
```
dongyookang DK 🚦   ~/ffplay/GolandProjects/xellos/vatz   ISSUE-499
ok      github.com/dsrvlabs/vatz/cmd    2.343s  coverage: 23.3% of statements
ok      github.com/dsrvlabs/vatz/manager/api    0.686s  coverage: 0.0% of statements [no tests to run]
ok …
```
> Update SDK to remove AlertTypes in CallResponse in struct

- Makefile
- cmd/cmd.go
- cmd/init.go
- cmd/plugin.go
- cmd/plugin_test.go
- cmd/start.go
- manager/executor/executor_test.go
- manager/executor/general_executor.go
- manager/healthcheck/general_healthcheck.go
- manager/plugin/db_test.go
- manager/plugin/plugin.go
- manager/plugin/plugin_test.go
- monitoring/prometheus/metric_test.go
- monitoring/prometheus/prometheus.go
- monitoring/prometheus/prometheus_test.go
- rpc/rpc.go
- rpc/rpc_test.go
---
close #344 
**Summary**
Update Codes to pass Golint
---
```shell
hg  ~/workspace/vatz   lint  golangci-lint run -v              
INFO [config_reader] Config search paths: [./ /Users/hg/workspace/vatz /Users/hg/workspace /Users/hg /Users /] 
INFO [lintersdb] Active 9 linters: [deadcode errcheck gosimple govet ineffassign staticcheck typecheck unused varcheck] 
INFO [loader] Go packages loading at mode 575 (exports_file|imports|name|types_sizes|compiled_files|deps|files) took 449.86046ms 
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 5.367997ms 
INFO …
```
> Update Codes to pass Golint

- .github/workflows/ci_coverage.yml
---
close #523 
**Summary**
Current coverage test is running on main branch only when PR is raised, which's wrong. 
I updated co_coverage.yml to run make test on target branch that include PR's update. 
---
> checkout only branch that is raised from to run make coverage test.

- .github/workflows/create-vatz-bi-weekly.yml
---
- **Related:** #560 
**Summary**
Fix the bug about not creation the discussion.
---
Before the this github action merge, we need to set the value like below.
- Secrets
- REPOSITORY_ID
- CATEGORY_ID
- Variables
- START_DATE=2024-06-05
> How to get the REPOSITORY_ID and CATEGORY_ID
> You can run the below code with editing the <YOUR_GITHUB_TOKEN>
> 
> ```sh
> #!/bin/bash
> 
> # GitHub Personal Access Token
> TOKEN=<YOUR_GITHUB_TOKEN>
> 
> # GitHub GraphQL API Endpoint
> URL="https://api.github.com/graphql"
> 
> # GraphQL Query
> QUERY='{
> "query": "query { repository(owner: \"dsrvlabs\", name: \"vatz\") { id discussionCategories(first: 10) { edges { node { id name …
```
> Fix the github action of creation bi weekly discussion

- cmd/init.go
- manager/config/config.go
- manager/dispatcher/discord.go
- manager/dispatcher/dispatcher.go
- manager/dispatcher/pagerduty.go
- manager/dispatcher/slack.go
- manager/dispatcher/telegram.go
- manager/executor/executor_test.go
- manager/executor/general_executor.go
- manager/plugin/plugin.go
- utils/utils.go
- Select plugin's dispatcher for notification by Flag
---
close #583
**Summary**
For watcher that we created via VATZ, We would like to set a notification method per plugins via flags. 
---
Setting a Flag on Config as below 
---
> 1) If no subscriptions are set: All messages will be sent to all dispatch_channels.
> 2) If subscriptions are set with a plugin name: Notifications will be sent only when the status changes for the specified plugins on dispatch_channels
```
subscriptions: 
- "Plugin names"
- "Plugin names"
- "Plugin names" 
```
```
default_reminder_schedule:
- "*/30 * …
```
> Send Notification via its Flag

- sdk/go.mod
- sdk/go.sum
---
- https://github.com/dsrvlabs/vatz/pull/603
- https://github.com/dsrvlabs/vatz/pull/601
**Summary**
This is an new PR to resolve both conflict on issues shown above. 
---
```
 make 
go test -v
=== RUN   TestRegister
2024-10-09T18:52:29-05:00 INF Register module=grpc
2024-10-09T18:52:29-05:00 INF Register module=grpc
2024-10-09T18:52:29-05:00 INF Register module=grpc
2024-10-09T18:52:29-05:00 INF Register module=grpc
2024-10-09T18:52:29-05:00 INF Register module=grpc
2024-10-09T18:52:29-05:00 INF Register module=grpc
2024-10-09T18:52:29-05:00 INF Register module=grpc
--- …
```
> Updated to fix dpendabot pointed out.
